[parity]
chain = "pib/chain.json"
no_download = true
base_path = "pib/state/chainstate"
keys_path = "pib/keys"

[ui]
disable = true

[rpc]
apis = ["eth","net","parity","web3","personal"]
interface = "0.0.0.0"

[websockets]
apis = ["eth","net","parity","web3","personal"]
interface = "0.0.0.0"
origins = ["all"]

[ipc]
disable = true

[secretstore]
disable = true

[network]
node_key = "{{network_key}}"
reserved_peers = "pib/peers.txt"

[account]
password = ["pib/account.pass"]

[mining]
engine_signer = "{{account_addr}}"
reseal_on_txs = "none"

